### ISSUE TITLE
Stopped working in the latest version of HA

### ISSUE THREAD

**Issue by i00** [rodpayne/home-assistant#1]
No longer appears to work for attributes in HA 0.103.6

**Comment by rodpayne** [comment]
What is the nature of it not working?  Does it give some kind of error message? What is it that you are trying to have it do? Was it working unchanged in previous versions?

(I am running 0.103.6 and have not noticed anything.)

**Comment by i00** [comment]
It sets states but I am trying to create / update an attribute:
Service: python_script.set_state
```YAML
entity_id: device_tracker.i00_phone
Location: test
```
The attribute doesn't get created or set.. no error

**Comment by rodpayne** [comment]
So is this a new thing that you are trying to do, or did it start with the upgrade to HA 0.103.6?

Do you have something like this in your automation, including `data` or `data_template`?
```
  action:
    - service: python_script.set_state
      data:
        entity_id: device_tracker.i00_phone
        location: test
```
You might be able to see more with logging enabled in `configuration.yaml`:
```
logger:
  default: warning
  logs:
    homeassistant.components.python_script.set_state.py: debug
```
