### ISSUE TITLE
Is it possible to apply set_state to multiple entities at once?

### ISSUE THREAD

**Issue by szawadski** [rodpayne/home-assistant#24]
I would like to have a list of entities to which I would like to apply a new state.
Currently, I am trying the following but it does not work.
```
action:
    - service: python_script.set_state
      data:
        entity_id:
          - sensor.edisio_2677633030_4cmd
          - sensor.edisio_2677633030_6cmd
          - sensor.edisio_60190726_1cmd
          - sensor.edisio_60190726_3cmd
          - sensor.edisio_60190726_5cmd
          - sensor.edisio_60190726_7cmd
          - sensor.edisio_60190726_8cmd
        state: "OFF"
```
Should it work or the code of the python script does not take lists into account. I don't understand its logic so I can't check myself.

**Comment by rodpayne** [comment]
No, as it stands right now, you would need to repeat the service call instead.
```
action:
    - service: python_script.set_state
      data:
        entity_id:
          - sensor.edisio_2677633030_4cmd
        state: "OFF"
    - service: python_script.set_state
      data:
        entity_id:
          - sensor.edisio_2677633030_6cmd
        state: "OFF"
```
This might be a good enhancement.
