### ISSUE TITLE
Lovelace HomeSeer WD200+/WX300 Card Status/Questions

### ISSUE THREAD

**Issue by rct** [rodpayne/home-assistant#25]
I just stumbled across this card (Sept 2024) while looking for the set_state.Python script.  I installed it and noticed I didn't see it update when I turned this switch on.  I have a 20+ HS-WD200+ and a couple of the 200 series fan controllers (4 LEDs instead of 7).

Does this card still work?

Is there a script (or something besides the card JavaScript) that I need to install to get the status of the LEDs from ZwaveJS?

Or is this only able to see when LEDs have been set manually (overriding the default brightness related statue)?

On a related note, I'm currently not utilizing the LEDs on the 20+ switches I have very smartly. Is there something I should be looking at in your repo?

Thanks for sharing your stuff!

**Comment by rodpayne** [comment]
Yes, I am still using this card with one HomeSeer WD200+ and one HomeSeer WX300.  And, yes, the card shows the settings of the LEDs when they are in Status Mode (rather than Normal Mode).

From the HS-WX300 user manual:

* **Status mode:** Individual LEDs can be controlled to reflect the status of nearly anything in the home. For example, one LED can be programmed to glow yellow when the garage door is open. Another LED can blink red when motion is sensed in the driveway. The possibilities are endless.
* **Switching between normal mode and status mode:** HS-WX300 switches operate in normal mode by default unless or until a status command is received. When that happens, normal mode is suspended and the switch goes into status mode. It will stay in status mode until all status LEDs are turned off. At that point, the switch will revert to normal mode.   

I have code in various automations to set each LED, like the following:
```
            - service: zwave_js.set_config_parameter
              target:
                area_id: house_status
              data:
                parameter: "22"
                value: Yellow
            - service: zwave_js.set_config_parameter
              data:
                parameter: LED 2 Blink Status
                value: "0"
              target:
                area_id: house_status
```
(The two dimmers that I have are used as reference for at-a-glance status of all of the doors as we are leaving or locking up for the night.  They both are set with the same `area_id` of `house_status` so that the automations can set both without individual calls.)

I will extract some of the automations and drop them in this repo as examples.
